name: go imports
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - name: run goimports
        run: goimports -w .
      - name: check for unformatted code
        run: git diff --exit-code
